#!/bin/sh
#/etc/init.d/relay
export PATH=$PATH:/usr/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules


case "$1" in
start)
forever -o /var/log/relay_operations/stdout.log start /home/pi/workspace.nodejs/relay_control/server/server.js >> /var/log/relay_operations/output.log 2>>/var/log/relay_operations/error.log
# exec forever --sourceDir=/home/pi/workspace.nodejs/relay_control/server -p /home/pi/workspace.nodejs/relay_control/server server.js  #scriptarguments
;;
stop)
forever stop /home/pi/workspace.nodejs/relay_control/server/server.js
# exec forever stop --sourceDir=/home/pi/workspace.nodejs/relay_control/server server.js
;;
restart)
forever stop /home/pi/workspace.nodejs/relay_control/server/server.js
sleep 2
forever -o /var/log/relay_operations/stdout.log start /home/pi/workspace.nodejs/relay_control/server/server.js >> /var/log/relay_operations/output.log 2>>/var/log/relay_operations/error.log
;;
*)
echo "Usage: /etc/init.d/relay {start|stop|restart}"
exit 1
;;
esac
exit 0
